sports_keywords = [
    'football', 'soccer', 'basketball', 'baseball', 'tennis', 'golf', 'rugby', 'hockey', 'cricket', 'match', 'game',
    'volleyball', 'swimming', 'cycling', 'running', 'marathon', 'athletics', 'surfing', 'skateboarding', 
    'skiing', 'snowboarding', 'climbing', 'gymnastics', 'wrestling', 'boxing', 'martial arts', 'karate', 
    'judo', 'taekwondo', 'fencing', 'archery', 'shooting', 'sailing', 'rowing', 'canoeing', 'kayaking', 
    'windsurfing', 'kitesurfing', 'fishing', 'hunting', 'motorsport', 'formula1', 'NASCAR', 'rallying', 
    'track and field', 'ice skating', 'figure skating', 'speed skating', 'badminton', 'table tennis', 
    'squash', 'bowling', 'billiards', 'pool', 'snooker', 'darts', 'lacrosse', 'handball', 'netball', 
    'ultimate frisbee', 'beach volleyball', 'beach soccer', 'beach rugby', 'beach tennis', 'softball', 
    'skateboarding', 'BMX', 'parkour', 'rock climbing', 'mountaineering', 'skydiving', 'bungee jumping', 
    'BASE jumping', 'cliff diving', 'paragliding', 'hang gliding', 'snowmobiling', 'snowshoeing', 
    'ice climbing', 'ice hockey', 'roller skating', 'roller derby', 'scootering', 'sled dog racing', 
    'cross-country skiing', 'biathlon', 'Nordic skiing', 'freestyle skiing', 'alpine skiing', 
    'ski mountaineering', 'ski jumping', 'ski flying', 'snowshoe running', 'freediving', 'spearfishing', 
    'finswimming', 'underwater rugby', 'underwater hockey', 'underwater target shooting', 
    'synchronized swimming', 'water polo', 'bodyboarding', 'body surfing', 'wakeboarding', 
    'water skiing', 'paddleboarding', 'rafting', 'parasailing', 'scuba diving', 'snorkeling', 
    'surf lifesaving', 'skiing', 'snowboarding', 'skimboarding', 'wakesurfing', 'river surfing', 
    'windsurfing', 'kitesurfing', 'wakeboarding', 'water skiing', 'jetskiing', 'paddleboarding', 
    'canoeing', 'kayaking', 'rowing', 'dragon boating', 'sailing', 'kayak polo', 'water basketball', 
    'underwater football', 'freediving', 'spearfishing', 'underwater photography', 'surfing', 
    'bodyboarding', 'windsurfing', 'kitesurfing', 'wakeboarding', 'skimboarding', 'surf lifesaving', 
    'sandboarding', 'snowboarding', 'skiing', 'ice skating', 'figure skating', 'speed skating', 
    'short track speed skating', 'ice hockey', 'ringette', 'bandy', 'broomball', 'ice stock sport', 
    'underwater hockey', 'underwater rugby', 'canoe polo', 'kayak polo', 'water polo', 'underwater football', 
    'freediving', 'spearfishing', 'underwater photography', 'underwater videography', 'surfing', 
    'bodyboarding', 'windsurfing', 'kitesurfing', 'wakeboarding', 'skimboarding', 'wake surfing', 
    'windsurfing', 'kitesurfing', 'longboarding', 'skateboarding', 'mountain biking', 'BMX', 'road cycling', 
    'track cycling', 'cyclocross', 'bike polo', 'bicycle motocross', 'bicycle trials', 'hill climbing', 
    'rock climbing', 'bouldering', 'sport climbing', 'trad climbing', 'free soloing', 'ice climbing', 
    'mountaineering', 'aid climbing', 'mixed climbing', 'big wall climbing', 'caving', 'canyoning', 
    'via ferrata', 'deep-water soloing', 'slacklining', 'mountain running', 'cross-country running', 
    'trail running', 'skyrunning', 'fell running', 'ultrarunning', 'road running', 'track and field', 
    'sprinting', 'middle-distance running', 'long-distance running', 'hurdles', 'steeplechase', 
    'racewalking', 'orienteering', 'rogaining', 'fell running', 'fell racing', 'fell running', 
    'ski mountaineering', 'snowshoe running', 'sled dog racing', 'cross-country skiing', 'biathlon', 
    'Nordic skiing', 'telemark skiing', 'ski orienteering', 'ski mountaineering', 'ski jumping', 
    'ski flying', 'freestyle skiing', 'alpine skiing', 'moguls', 'half-pipe', 'big air', 'ski cross', 
    'slopestyle', 'snowboarding', 'freestyle snowboarding', 'alpine snowboarding', 'big air', 'half-pipe', 
    'slopestyle', 'boardercross', 'snowboard cross', 'cross-country snowboarding', 'splitboarding', 
    'alpine touring', 'snowshoeing', 'ice skating', 'figure skating', 'speed skating', 'short track speed skating', 
    'ice dancing', 'synchronized skating', 'freestyle ice skating', 'ice hockey', 'ringette', 'bandy', 
    'broomball', 'rinkball', 'ice stock sport', 'underwater hockey', 'underwater rugby', 'canoe polo', 
    'kayak polo', 'water polo', 'underwater football', 'underwater rugby', 'underwater target shooting', 
    'underwater orienteering', 'underwater photography', 'underwater videography', 'freediving', 'spearfishing', 
    'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 
    'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 
    'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 
    'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 
    'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 'freediving', 
    'spearfishing', 'snorkeling', 'scuba diving', 'technical diving', 'cave diving', 'ice diving', 'wreck diving', 
    'rebreather diving', 'surface-supplied diving', 'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 
    'technical diving', 'cave diving', 'ice diving', 'wreck diving', 'rebreather diving', 'surface-supplied diving', 
    'freediving', 'spearfishing', 'snorkeling', 'scuba diving', 'technical diving']
