sports_lexicon = {
    'goal': 0.8,
    'score': 0.7,
    'win': 0.9,
    'victory': 0.9,
    'champion': 0.9,
    'triumph': 0.8,
    'defeat': -0.8,
    'loss': -0.7,
    'draw': 0.3,
    'tie': 0.3,
    'match': 0.5,
    'game': 0.5,
    'team': 0.6,
    'player': 0.6,
    'coach': 0.4,
    'fans': 0.7,
    'supporters': 0.7,
    'stadium': 0.6,
    'pitch': 0.6,
    'field': 0.6,
    'court': 0.6,
    'referee': -0.4,
    'umpire': -0.4,
    'league': 0.5,
    'tournament': 0.6,
    'season': 0.5,
    'training': 0.4,
    'practice': 0.4,
    'athletes': 0.6,
    'sportsmanship': 0.7,
    'record': 0.5,
    'medal': 0.8,
    'podium': 0.7,
    'athlete': 0.6,
    'rival': -0.6,
    'rivalry': -0.7,
    'derby': -0.7,
    'injury': -0.6,
    'comeback': 0.7,
    'performance': 0.6,
    'legend': 0.8,
    'icon': 0.7,
    'hero': 0.8,
    'legendary': 0.9,
    'inspiration': 0.8,
    'underdog': 0.6,
    'spectacle': 0.6,
    'exciting': 0.7,
    'thrilling': 0.8,
    'intense': 0.7,
    'nail-biting': 0.8,
    'dramatic': 0.7,
    'epic': 0.8,
    'memorable': 0.7,
    'historic': 0.8,
    'unforgettable': 0.9,
    'spectacular': 0.8,
    'amazing': 0.8,
    'fantastic': 0.8,
    'incredible': 0.8,
    'awesome': 0.8,
    'remarkable': 0.8,
    'unbelievable': 0.8,
    'phenomenal': 0.9,
    'superb': 0.8,
    'brilliant': 0.8,
    'impressive': 0.8,
    'outstanding': 0.8,
    'terrific': 0.8,
    'excellent': 0.8,
    'fabulous': 0.8,
    'outstanding': 0.8,
    'amazing': 0.8,
    'formidable': 0.8,
    'wonderful': 0.8,
    'great': 0.8,
    'formidable': 0.8,
    'fascinating': 0.7,
    'captivating': 0.7,
    'electrifying': 0.8,
    'engrossing': 0.7,
    'riveting': 0.8,
    'compelling': 0.7,
    'gripping': 0.7,
    'mesmerizing': 0.8,
    'exhilarating': 0.8,
    'heart-pounding': 0.8,
    'heart-stopping': 0.8,
    'breathtaking': 0.9,
    'jaw-dropping': 0.9,
    'eye-popping': 0.9,
    'mind-blowing': 0.9,
     'football': 0.6,
    'soccer': 0.6,
    'basketball': 0.6,
    'tennis': 0.6,
    'baseball': 0.6,
    'volleyball': 0.6,
    'rugby': 0.6,
    'hockey': 0.6,
    'golf': 0.6,
    'cricket': 0.6,
    'boxing': 0.6,
    'wrestling': 0.6,
    'athletics': 0.6,
    'swimming': 0.6,
    'cycling': 0.6,
    'running': 0.6,
    'marathon': 0.6,
    'surfing': 0.6,
    'skateboarding': 0.6,
    'skiing': 0.6,
    'snowboarding': 0.6,
    'climbing': 0.6,
    'surfing': 0.6,
    'kayaking': 0.6,
    'canoeing': 0.6,
    'rowing': 0.6,
    'sailing': 0.6,
    'fishing': 0.6,
    'hunting': 0.6,
    'shooting': 0.6,
    'archery': 0.6,
    'motorsport': 0.6,
    'formula1': 0.6,
    'nascar': 0.6,
    'racing': 0.6,
    'boxing': 0.6,
    'wrestling': 0.6,
    'mma': 0.6,
    'ufc': 0.6,
    'karate': 0.6,
    'judo': 0.6,
    'taekwondo': 0.6,
    'gymnastics': 0.6,
    'dancing': 0.6,
    'cheerleading': 0.6,
    'fitness': 0.6,
    'exercise': 0.6,
    'training': 0.6,
    'workout': 0.6,
    'gym': 0.6,
    'athlete': 0.6,
    'sportsmanship': 0.6,
    'olympics': 0.7,
    'paralympics': 0.7,
    'sportscenter': 0.6,
    'espn': 0.6,
    'nba': 0.6,
    'nfl': 0.6,
    'mlb': 0.6,
    'nhl': 0.6,
    'fifa': 0.6,
    'uefa': 0.6,
    'nascar': 0.6,
    'worldcup': 0.7,
    'superbowl': 0.7,
    'championship': 0.6,
    'tournament': 0.6,
    'league': 0.6,
    'team': 0.6,
    'player': 0.6,
    'coach': 0.6,
    'stadium': 0.6,
    'fans': 0.6,
    'supporters': 0.6,
    'athlete': 0.6,
    'fitness': 0.6,
    'champion': 0.7,
    'medal': 0.7,
    'podium': 0.7,
    'record': 0.6,
     '⚽': 0.6,  # Soccer Ball
    '🏀': 0.6,  # Basketball
    '🏈': 0.6,  # American Football
    '⚾': 0.6,  # Baseball
    '🎾': 0.6,  # Tennis
    '🏐': 0.6,  # Volleyball
    '🏉': 0.6,  # Rugby Football
    '🥎': 0.6,  # Softball
    '🏏': 0.6,  # Cricket
    '🏑': 0.6,  # Field Hockey
    '🏒': 0.6,  # Ice Hockey
    '🥍': 0.6,  # Lacrosse
    '🏓': 0.6,  # Ping Pong
    '🏸': 0.6,  # Badminton
    '🥊': 0.6,  # Boxing Glove
    '🥋': 0.6,  # Martial Arts Uniform
    '⛷️': 0.6,  # Skier
    '🏂': 0.6,  # Snowboarder
    '🪂': 0.6,  # Parachute
    '🏋️': 0.6,  # Weight Lifter
    '🏌️': 0.6,  # Golfer
    '🏄': 0.6,  # Surfer
    '🚣': 0.6,  # Person Rowing Boat
    '🧗': 0.6,  # Person Climbing
    '🚴': 0.6,  # Person Biking
    '🚵': 0.6,  # Mountain Biker
    '🏇': 0.6,  # Horse Racing
    '🧘': 0.6,  # Person in Lotus Position
    '🏋️‍♂️': 0.6,  # Man Weight Lifting
    '🏋️‍♀️': 0.6,  # Woman Weight Lifting
    '🏌️‍♂️': 0.6,  # Man Golfer
    '🏌️‍♀️': 0.6,  # Woman Golfer
    '🏄‍♂️': 0.6,  # Man Surfing
    '🏄‍♀️': 0.6,  # Woman Surfing
    '🚣‍♂️': 0.6,  # Man Rowing Boat
    '🚣‍♀️': 0.6,  # Woman Rowing Boat
    'hashtag': 0.5,
    'retweet': 0.5,
    'like': 0.5,
    'share': 0.5,
    'comment': 0.5,
    'post': 0.5,
    'tweet': 0.5,
    'status': 0.5,
    'mention': 0.5,
    'viral': 0.6,
    'trending': 0.6,
    'influencer': 0.6,
    'followers': 0.5,
    'following': 0.5,
    'subscribe': 0.5,
    'notification': 0.5,
    'update': 0.5,
    'story': 0.5,
    'feed': 0.5,
    'live': 0.5,
    'stream': 0.5,
    'channel': 0.5,
    'profile': 0.5,
    'bio': 0.5,
    'avatar': 0.5,
    'caption': 0.5,
    'emojis': 0.5,
    'meme': 0.6,
    'gif': 0.5,
    'reaction': 0.5,
    'emoji': 0.5,
    'mood': 0.5,
    'commentary': 0.5,
    'engagement': 0.5,
    'analytics': 0.5,
    'algorithm': 0.5,
    'tag': 0.5,
    'explore': 0.5,
    'scroll': 0.5,
    'swipe': 0.5,
    'click': 0.5,
    'link': 0.5,
    'bio': 0.5,
    'DM': 0.5,
    'direct message': 0.5,
    'story': 0.5,
    'snap': 0.5,
    'snapchat': 0.5,
    'selfie': 0.5,
    'filter': 0.5,
    'tag': 0.5,
    'geotag': 0.5,
    'post': 0.5,
    'feed': 0.5,
    'trend': 0.5,
    'vlog': 0.5,
    'podcast': 0.5,
    'live': 0.5,
    'stories': 0.5,
    'content': 0.5,
    'creator': 0.5,
    'followers': 0.5,
    'following': 0.5,
    'likes': 0.5,
    'comments': 0.5,
    'shares': 0.5,
    'views': 0.5,
    'engagement': 0.5,
    'algorithm': 0.5,
    'explore page': 0.5,
    'timeline': 0.5,
    'profile': 0.5,
    'bio': 0.5,
    'avatar': 0.5,
    'layout': 0.5,
    'theme': 0.5,
    'header': 0.5,
    'display picture': 0.5,
    'tweet': 0.5,
    'retweet': 0.5,
    'quote tweet': 0.5,
    'thread': 0.5,
    'reply': 0.5,
    'like': 0.5,
    'share': 0.5,
    'comment': 0.5,
    'notifications': 0.5,
    'mentions': 0.5,
    'inbox': 0.5,
    'explore': 0.5,
    'trending': 0.5,
    'viral': 0.5,
    'popular': 0.5,
    'featured': 0.5,
    'repost': 0.5,
    'explore page': 0.5,
    'search': 0.5,
    'discover': 0.5,
    'recommended': 0.5,
    'for you': 0.5,
    'suggested': 0.5,
    'customized': 0.5,
    'personalized': 0.5,
    'relevant': 0.5,
    'related': 0.5,
    'explore tab': 0.5,
    'following': 0.5,
    'explore': 0.5,
    'discover': 0.5,
    'trending': 0.5,
    'viral': 0.5,
    'popular': 0.5,
    'featured': 0.5,
    'repost': 0.5,
    'explore page': 0.5,
    'search': 0.5,
    'discover': 0.5,
    'recommended': 0.5,
    'for you': 0.5,
    'suggested': 0.5,
    'customized': 0.5,
    'personalized': 0.5,
    'relevant': 0.5,
    'related': 0.5,
    'explore tab': 0.5,
    'following': 0.5,
    'followers': 0.5,
    'follow': 0.5,
    'like': 0.5,
    'share': 0.5,
    'comment': 0.5,
    'post': 0.5,
    'story': 0.5,
    'feed': 0.5,
    'status': 0.5,
    'tweet': 0.5,
    'retweet': 0.5,
    'quote tweet': 0.5,
    'like': 0.5,
    'reply': 0.5,
    'share': 0.5,
    'comment': 0.5,
    'post': 0.5,
    'story': 0.5,
    'feed': 0.5,
    'status': 0.5,
    'tweet': 0.5,
    'retweet': 0.5,
    'quote tweet': 0.5,
    'like': 0.5,
    'reply': 0.5,
    'share': 0.5,
    'comment': 0.5,
    'notifications': 0.5,
    'mentions': 0.5,
    'inbox': 0.5,
    'engage': 0.5,
    'interact': 0.5,
    'connect': 0.5,
    'communicate': 0.5,
     'football': 0.6,
    'soccer': 0.6,
    'basketball': 0.6,
    'tennis': 0.6,
    'baseball': 0.6,
    'volleyball': 0.6,
    'rugby': 0.6,
    'hockey': 0.6,
    'golf': 0.6,
    'cricket': 0.6,
    'boxing': 0.6,
    'wrestling': 0.6,
    'athletics': 0.6,
    'swimming': 0.6,
    'cycling': 0.6,
    'running': 0.6,
    'marathon': 0.6,
    'surfing': 0.6,
    'skateboarding': 0.6,
    'skiing': 0.6,
    'snowboarding': 0.6,
    'climbing': 0.6,
    'surfing': 0.6,
    'kayaking': 0.6,
    'canoeing': 0.6,
    'rowing': 0.6,
    'sailing': 0.6,
    'fishing': 0.6,
    'hunting': 0.6,
    'shooting': 0.6,
    'archery': 0.6,
    'motorsport': 0.6,
    'formula1': 0.6,
    'nascar': 0.6,
    'racing': 0.6,
    'boxing': 0.6,
    'wrestling': 0.6,
    'mma': 0.6,
    'ufc': 0.6,
    'karate': 0.6,
    'judo': 0.6,
    'taekwondo': 0.6,
    'gymnastics': 0.6,
    'dancing': 0.6,
    'cheerleading': 0.6,
    'fitness': 0.6,
    'exercise': 0.6,
    'training': 0.6,
    'workout': 0.6,
    'gym': 0.6,
    'athlete': 0.6,
    'sportsmanship': 0.6,
    'olympics': 0.7,
    'paralympics': 0.7,
    'sportscenter': 0.6,
    'espn': 0.6,
    'nba': 0.6,
    'nfl': 0.6,
    'mlb': 0.6,
    'nhl': 0.6,
    'fifa': 0.6,
    'uefa': 0.6,
    'nascar': 0.6,
    'worldcup': 0.7,
    'superbowl': 0.7,
    'championship': 0.6,
    'tournament': 0.6,
    'league': 0.6,
    'team': 0.6,
    'player': 0.6,
    'coach': 0.6,
    'stadium': 0.6,
    'fans': 0.6,
    'supporters': 0.6,
    'athlete': 0.6,
    'fitness': 0.6,
    'champion': 0.7,
    'medal': 0.7,
    'podium': 0.7,
    'record': 0.6,
    'injury': -0.6,
    'defeat': -0.6,
    'incompetent': -0.6,
    'disqualification': -0.7,
    'foul': -0.6,
    'misconduct': -0.6,
    'penalty': -0.6,
    'suspension': -0.6,
    'failure': -0.6,
    'loss': -0.6,
    'disappointment': -0.6,
    'disheartening': -0.6,
    'frustrating': -0.6,
    'choking': -0.7,
    'collapse': -0.7,
    'blowout': -0.6,
    'tragic': -0.7,
    'devastating': -0.7,
    'heartbreaking': -0.7,
    'crushing': -0.7,
    'meltdown': -0.7,
    'injured': -0.6,
    'defeated': -0.6,
    'struggle': -0.5,
    'injury-prone': -0.6,
    'underperforming': -0.6,
    'underachieving': -0.6,
    'negligent': -0.6,
    'incompetence': -0.6,
    'disqualified': -0.7,
    'foul play': -0.6,
    'misconduct': -0.6,
    'penalized': -0.6,
    'suspended': -0.6,
    'failure': -0.6,
    'losing streak': -0.6,
    'defeatist': -0.6,
    'letdown': -0.6,
    'frustration': -0.6,
    'disheartened': -0.6,
    'choked': -0.7,
    'collapsed': -0.7,
    'blowout loss': -0.6,
    'tragedy': -0.7,
    'devastation': -0.7,
    'heartbreak': -0.7,
    'crushed': -0.7,
    'meltdown': -0.7,

}
